---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Europe/London
      time: "06:00"
    labels:
      - dependencies
    allow:
      - dependency-name: peter-evans/create-pull-request
