#!/bin/bash -e

# Copyright © 2020-2022 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

if [ -z "$ANDROID_NDK_HOME" ]; then
    echo "ANDROID_NDK_HOME is not set" >&2
    exit 1
fi

TARGET=${TARGET:-armv7a-linux-androideabi}

if [[ "$TARGET" =~ ^(aarch64|x86_64)- ]]; then
    PLATFORM=21
else
    PLATFORM=16
fi

toolchain=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
version=$(cat rsync-version)

[ -d buildinfo ] || mkdir buildinfo
echo "$version" > buildinfo/release
grep Pkg.Revision "$ANDROID_NDK_HOME/source.properties" | \
    cut -d ' ' -f 3 >> buildinfo/ndkver

git clone --branch "$version" --depth 1 https://github.com/WayneD/rsync.git
cd rsync

./configure --host="$TARGET" --disable-md2man \
    --disable-lz4 --disable-openssl --disable-xxhash --disable-zstd \
    AR="$toolchain/bin/llvm-ar" \
    CC="$toolchain/bin/$TARGET$PLATFORM-clang" \
    RANLIB="$toolchain/bin/llvm-ranlib" \
    STRIP="$toolchain/bin/llvm-strip"

make
