#!/bin/bash -e

# Copyright © 2020-2021 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

if [ -z "$ANDROID_NDK_HOME" ]; then
    if [ "$ANDROID_HOME" ]; then
        export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
    else
        echo "Either ANDROID_NDK_HOME or ANDROID_HOME must be set" >&2
        exit 1
    fi
fi

TARGET=${TARGET:-armv7a-linux-androideabi}

if [[ "$TARGET" =~ ^(aarch64|x86_64)- ]]; then
    PLATFORM=21
else
    PLATFORM=16
fi

toolchain=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
version=$(cat rsync-version)

git clone --branch "$version" --depth 1 https://github.com/WayneD/rsync.git
cd rsync

./configure --host="$TARGET" --disable-md2man --disable-simd --disable-asm \
    --disable-lz4 --disable-openssl --disable-xxhash --disable-zstd \
    AR="$toolchain/bin/llvm-ar" \
    CC="$toolchain/bin/$TARGET$PLATFORM-clang" \
    RANLIB="$toolchain/bin/llvm-ranlib" \
    STRIP="$toolchain/bin/llvm-strip"

make
