---
# Copyright © 2020-2022 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build
on:
  push:
    branches-ignore:
      - dependabot/**
      - update-version
  pull_request:
  schedule:
    - cron: '30 12 * * 5'

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7a-linux-androideabi
          - aarch64-linux-android
          - i686-linux-android
          - x86_64-linux-android
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build script
        run: |
          ndk="$($ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
                 --list_installed | sed -E 's/( +[|] +)/|/g;s/ +$//' | \
                 grep '^  ndk' | cut -d '|' -f 4 | sort | head -n1)"
          ANDROID_NDK_HOME="$ANDROID_HOME/$ndk" ./build
        env:
          TARGET: ${{ matrix.target }}

      - name: Collect binaries and build info
        run: |
          mkdir output
          cp rsync/rsync output
          cp rsync/COPYING output/COPYING.txt

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: output

      - name: Upload build info as artifact
        uses: actions/upload-artifact@v3
        with:
          name: buildinfo
          path: buildinfo

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Fetch artifacts
        uses: actions/download-artifact@v4

      - name: Extract info to environment vars
        run: |
          echo "BUILD_RELEASE=$(cat buildinfo/release)" >> "$GITHUB_ENV"
          echo "NDK_VERSION=$(cat buildinfo/ndkver)" >> "$GITHUB_ENV"
          echo "JAR_VERSION=$(cat buildinfo/release | sed -e 's/^v//')" \
                >> "$GITHUB_ENV"

      - name: Latest release tag name
        id: latest_release
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const query = `query release($owner:String!, $repo:String!) {
              repository(owner:$owner, name:$repo) {
                releases(first:1, orderBy:{field:CREATED_AT, direction:DESC}) {
                  nodes {
                    tagName
                  }
                }
              }
            }`
            const vars = {
              owner: context.repo.owner,
              repo: context.repo.repo,
            }
            const result = await github.graphql(query, vars)
            return result.repository.releases.nodes[0].tagName

      - name: Package assets
        run: |
          zip --junk-paths rsync-armv7a-linux-androideabi.zip \
              armv7a-linux-androideabi/*
          zip --junk-paths rsync-aarch64-linux-android.zip \
              aarch64-linux-android/*
          zip --junk-paths rsync-i686-linux-android.zip \
              i686-linux-android/*
          zip --junk-paths rsync-x86_64-linux-android.zip \
              x86_64-linux-android/*

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 11

      - name: Package JAR
        run: |
          mkdir -p lib/armeabi-v7a lib/arm64-v8a lib/x86 lib/x86_64 META-INF
          cp -p armv7a-linux-androideabi/rsync lib/armeabi-v7a/librsync.so
          cp -p aarch64-linux-android/rsync lib/arm64-v8a/librsync.so
          cp -p i686-linux-android/rsync lib/x86/librsync.so
          cp -p x86_64-linux-android/rsync lib/x86_64/librsync.so
          cp -p aarch64-linux-android/COPYING.txt META-INF/LICENSE
          jar cf android-rsync.jar lib META-INF

      - name: Create release
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.BUILD_RELEASE }}
          release_name: ${{ env.BUILD_RELEASE }}
          prerelease: ${{ contains(env.BUILD_RELEASE, 'pre') }}
          body: >
            rsync binary built for Android with NDK version
            ${{ env.NDK_VERSION }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload armv7a-linux-androideabi zip asset
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rsync-armv7a-linux-androideabi.zip
          asset_name: rsync-armv7a-linux-androideabi.zip
          asset_content_type: application/zip

      - name: Upload aarch64-linux-android zip asset
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rsync-aarch64-linux-android.zip
          asset_name: rsync-aarch64-linux-android.zip
          asset_content_type: application/zip

      - name: Upload i686-linux-android zip asset
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rsync-i686-linux-android.zip
          asset_name: rsync-i686-linux-android.zip
          asset_content_type: application/zip

      - name: Upload x86_64-linux-android zip asset
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rsync-x86_64-linux-android.zip
          asset_name: rsync-x86_64-linux-android.zip
          asset_content_type: application/zip

      - name: Upload JAR asset
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android-rsync.jar
          asset_name: android-rsync.jar
          asset_content_type: application/java-archive

      - name: Upload JAR to package registry
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          !contains(env.BUILD_RELEASE, 'pre')
        run: |
          mvn --batch-mode deploy:deploy-file \
            -DgroupId=com.nerdoftheherd \
            -DartifactId=android-rsync \
            -Dversion="${{ env.JAR_VERSION }}" \
            -Dfile=android-rsync.jar \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/ribbons/android-rsync \
            -DgeneratePom.description="rsync binaries built for Android with \
          NDK version ${{ env.NDK_VERSION }}."
        env:
          GITHUB_TOKEN: ${{ github.token }}
