---
# Copyright © 2020-2024 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build
on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
  schedule:
    - cron: '30 12 * * 5'

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    if: github.event_name != 'push' ||
        github.ref != 'refs/heads/update-version' ||
        github.event.head_commit.committer.name == 'github-actions[bot]'
    strategy:
      matrix:
        target:
          - armv7a-linux-androideabi
          - aarch64-linux-android
          - i686-linux-android
          - x86_64-linux-android
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build script
        run: |
          ndk="$($ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
                 --list_installed | sed -E 's/( +[|] +)/|/g;s/ +$//' | \
                 grep '^  ndk' | cut -d '|' -f 4 | sort | head -n1)"
          ANDROID_NDK_HOME="$ANDROID_HOME/$ndk" ./build
        env:
          TARGET: ${{ matrix.target }}

      - name: Collect binaries and build info
        run: |
          mkdir output
          cp rsync/rsync output
          cp rsync/COPYING output/COPYING.txt

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: output

      - name: Upload build info as artifact
        if: matrix.target == 'armv7a-linux-androideabi'
        uses: actions/upload-artifact@v4
        with:
          name: buildinfo
          path: buildinfo

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: Fetch artifacts
        uses: actions/download-artifact@v4

      - name: Extract info to environment vars
        run: |
          echo "BUILD_RELEASE=$(cat buildinfo/release)" >> "$GITHUB_ENV"
          echo "NDK_VERSION=$(cat buildinfo/ndkver)" >> "$GITHUB_ENV"
          echo "JAR_VERSION=$(cat buildinfo/release | sed -e 's/^v//')" \
                >> "$GITHUB_ENV"

      - name: Latest release tag name
        id: latest_release
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const query = `query release($owner:String!, $repo:String!) {
              repository(owner:$owner, name:$repo) {
                releases(first:1, orderBy:{field:CREATED_AT, direction:DESC}) {
                  nodes {
                    tagName
                  }
                }
              }
            }`
            const vars = {
              owner: context.repo.owner,
              repo: context.repo.repo,
            }
            const result = await github.graphql(query, vars)
            return result.repository.releases.nodes[0].tagName

      - name: Package assets
        run: |
          zip --junk-paths rsync-armv7a-linux-androideabi.zip \
              armv7a-linux-androideabi/*
          zip --junk-paths rsync-aarch64-linux-android.zip \
              aarch64-linux-android/*
          zip --junk-paths rsync-i686-linux-android.zip \
              i686-linux-android/*
          zip --junk-paths rsync-x86_64-linux-android.zip \
              x86_64-linux-android/*

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 11

      - name: Package JAR
        run: |
          mkdir -p lib/armeabi-v7a lib/arm64-v8a lib/x86 lib/x86_64 META-INF
          cp -p armv7a-linux-androideabi/rsync lib/armeabi-v7a/librsync.so
          cp -p aarch64-linux-android/rsync lib/arm64-v8a/librsync.so
          cp -p i686-linux-android/rsync lib/x86/librsync.so
          cp -p x86_64-linux-android/rsync lib/x86_64/librsync.so
          cp -p aarch64-linux-android/COPYING.txt META-INF/LICENSE
          jar cf android-rsync.jar lib META-INF

      - name: Create release
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            console.log("Creating release")

            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.BUILD_RELEASE,
              name: process.env.BUILD_RELEASE,
              prerelease: process.env.BUILD_RELEASE.includes('pre'),
              body: "rsync binary built for Android with NDK version " +
                    process.env.NDK_VERSION,
            })

            const assets = [
              'rsync-armv7a-linux-androideabi.zip',
              'rsync-aarch64-linux-android.zip',
              'rsync-i686-linux-android.zip',
              'rsync-x86_64-linux-android.zip',
              'android-rsync.jar',
            ]

            for(const asset of assets) {
              console.log("Uploading " + asset)
              await github.rest.repos.uploadReleaseAsset({
                headers: {
                  "content-type": asset.endsWith(".jar") ?
                    "application/java-archive" : "application/zip",
                },
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.data.id,
                data: fs.readFileSync(asset),
                name: asset,
              })
            }

      - name: Upload JAR to package registry
        if: >
          env.BUILD_RELEASE != steps.latest_release.outputs.result &&
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          !contains(env.BUILD_RELEASE, 'pre')
        run: |
          mvn --batch-mode deploy:deploy-file \
            -DgroupId=com.nerdoftheherd \
            -DartifactId=android-rsync \
            -Dversion="${{ env.JAR_VERSION }}" \
            -Dfile=android-rsync.jar \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/ribbons/android-rsync \
            -DgeneratePom.description="rsync binaries built for Android with \
          NDK version ${{ env.NDK_VERSION }}."
        env:
          GITHUB_TOKEN: ${{ github.token }}
