---
# Copyright © 2021 Matt Robinson
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Create PR if new version
on:
  workflow_dispatch:
  schedule:
    - cron: '05 00 * * 1-5'

env:
  SRC_OWNER: WayneD
  SRC_REPO: rsync

jobs:
  update-version:
    name: Create PR if new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.ACTIONS_SSH_PRIVATE_KEY }}

      - name: Latest upstream release tag name
        id: latest_release
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            const query = `query release($owner:String!, $repo:String!) {
              repository(owner:$owner, name:$repo) {
                refs(refPrefix:"refs/tags/", first:1,
                     orderBy:{field:TAG_COMMIT_DATE, direction:DESC}) {
                  edges {
                    node {
                      name
                    }
                  }
                }
              }
            }`
            const vars = {
              owner: process.env.SRC_OWNER,
              repo: process.env.SRC_REPO,
            }
            const result = await github.graphql(query, vars)
            return result.repository.refs.edges[0].node.name

      - name: Update version file
        run: echo "${{ steps.latest_release.outputs.result }}"
          > "${SRC_REPO}-version"

      - name: Create / update pull request if necessary
        # yamllint disable-line rule:line-length
        uses: peter-evans/create-pull-request@f094b77505fb89581e68a1163fbd2fffece39da1
        with:
          author: github-actions[bot]
            <41898282+github-actions[bot]@users.noreply.github.com>
          committer: github-actions[bot]
            <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: Update rsync to
            ${{ steps.latest_release.outputs.result }}
          title: Update rsync to ${{ steps.latest_release.outputs.result }}
          body: >
            Updates the version of rsync to be built to
            ${{ steps.latest_release.outputs.result }}.
          branch: update-version
